// Code generated by options-gen. DO NOT EDIT.
package healthcheck

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from variable
	o.logger = defaultOptions.logger

	o.setCheckStatus = defaultOptions.setCheckStatus

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLogger(opt ILogger) OptOptionsSetter {
	return func(o *Options) {
		o.logger = opt

	}
}

func WithSetCheckStatus(opt func(checkID string, isReady Status)) OptOptionsSetter {
	return func(o *Options) {
		o.setCheckStatus = opt

	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("setCheckStatus", _validate_Options_setCheckStatus(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_setCheckStatus(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.setCheckStatus, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `setCheckStatus` did not pass the test: %w", err)
	}
	return nil
}
